test fail output step color

diff --git a/.github/workflows/slack_bot.yaml b/.github/workflows/slack_bot.yaml
--- a/.github/workflows/slack_bot.yaml
+++ b/.github/workflows/slack_bot.yaml
@@ -17,6 +17,7 @@ jobs:
           id: fail-step
           run: |
             ./payload_modify.bash
+            echo "::set-output name=failed::$(if [ $? -eq 0 ]; then echo 'false'; else echo 'true'; fi)"
           continue-on-error: true
 
         - name: Set color based on the previous step
